#cloud-config
users:
  - name: ningu
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChqOktu5wgPsVy00sgBTdiYxOm2YBgFG5/if1rgTaLRmSnKFdQi/jBLx1J/7+NW/mlVaun8rC2HfZk+o9k6t1wHHd4fayDNYbsE69eJNbzo3K60QfnjnIK6bvkxRKXcXypdi+8Va4MX2V855eGJpW5emvPEmA3Joeiz7tDH+Li75AV1Qq2d33edbXLRfudn5X77bF/Hq30dgJN/y/6d2UCaX0kt5QFP2HHR6uM4K7v3g7iy1A6xBiIRAGVq5t0vvQQVPcaUfoX8EAz2rnSCL3KI9qAKI7FiSQFUyHY8NVQiB3Rk1NMcgILttMLgDhWeBAO99qJuz8oikTtKFEZrSq0q8TE+XxLF39j6t2AZU1W0zf8N3+fqxOnXBzuGaMZ9xB9G38qzVU/jg6CEdP9tRJXXjYb2+Rs9+Z4O9YyJAsDqXpSCllpL2/l4h8KUN+zfWeR3fqTL6pELoh0CXEdNGftLsvsx/SZkrO+d81PlW823ri4ubeNXH/ulnBxzxiZB+h1dObLLxWbavUUTxxIpEY4tO619HsG3dGM78zz3OzNiWuMfZoZvw9nWdY3bO8Y08QpSGvdjGIEqjXBhajv/xfA8wsO+8QW3MGupPDta0R3S3YSKpaqnne+ErXRKvzaCSikkZkPPUKd5eTFGe9d2B1XQd64nXH9hjA5WQUNCCZ7/Q== ningunpenk@hotmail.com

packages:
  - curl
  - wget
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - python
  - iptables-persistent
  - gnupg-agent
  - unzip
  - openjdk-11-jdk
  - openjdk-11-jre
  - git
  - jq
package_update: true
package_upgrade: true

write_files:
  - content: |
      #!/bin/bash
      DOCKER_NAME=$1
      CURRENT_TAG=$(cat /etc/docker/compose/kanban-board/docker-compose.yml | grep $DOCKER_NAME | cut -d ':' -f3-)

      REMOTE_SHA=$(curl --silent -L https://github.com/users/iiglesiasg/packages/container/${DOCKER_NAME}/ | grep "code>sha256:" | cut -d ':' -f2- | rev | cut -d '<' -f2- | rev)
      DAEMON_SHA=$(docker inspect ghcr.io/iiglesiasg/${DOCKER_NAME}:${CURRENT_TAG} | jq '.[].RepoDigests' | grep ghcr.io/iiglesiasg/${DOCKER_NAME} | cut -d ':' -f2- | tr -d '"')

      if [[ $DAEMON_SHA != $REMOTE_SHA ]];
      then
          UPSTREAM_IMAGE=$(curl --silent -L https://github.com/users/iiglesiasg/packages/container/${DOCKER_NAME} | grep "docker pull ghcr.io/iiglesiasg/${DOCKER_NAME}" | cut -d '"' -f2- | tr -d '"' | tr -d '>'| cut -d ' ' -f3-)
          UPSTREAM_TAG=$(echo $UPSTREAM_IMAGE | grep $DOCKER_NAME | cut -d ':' -f2-)
          docker pull $UPSTREAM_IMAGE
          cd ~/kanban-board
          git pull
          sed -i "s/${DOCKER_NAME}:${CURRENT_TAG}/${DOCKER_NAME}:${UPSTREAM_TAG}/g" /etc/docker/compose/kanban-board/docker-compose.yml
          cp /etc/docker/compose/kanban-board/docker-compose.yml ~/kanban-board/docker-compose.yml
      fi;
    path: /etc/docker/compose/kanban-board/cd-convergence.sh
  - content: |
      [Unit]
      Description=%i service with docker compose
      Requires=docker.service
      After=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=true
      WorkingDirectory=/etc/docker/compose/%i
      ExecStart=/usr/local/bin/docker-compose up -d --remove-orphans
      ExecStop=/usr/local/bin/docker-compose down

      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/docker-compose@.service
  - content: |
      * * * * * /etc/docker/compose/kanban-board/cd-convergence.sh kanban-board_kanban-ui
      * * * * * /etc/docker/compose/kanban-board/cd-convergence.sh kanban-board_kanban-app
    path: /etc/docker/compose/kanban-board/crontab-job

runcmd:
  - swapoff -a
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
  - sudo apt-add-repository https://cli.github.com/packages
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  - sudo apt update
  - sudo apt install docker-ce gh -y
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo sysctl -w vm.max_map_count=262144
  - sudo sysctl -w fs.file-max=65536
  - sudo sysctl -p
  - ulimit -n 65536
  - ulimit -u 4096
  - mkdir -p /etc/docker/compose/sonar
  - wget https://raw.githubusercontent.com/SonarSource/docker-sonarqube/master/example-compose-files/sq-with-postgres/docker-compose.yml
  - sudo mv docker-compose.yml /etc/docker/compose/sonar/
  - systemctl enable docker-compose@sonar && systemctl start docker-compose@sonar
#  - curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && sudo mv container-diff-linux-amd64 /usr/local/bin/container-diff
  - echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
  - touch /opt/ready.txt
  - reboot
