---
name: JavaApp CI Flow

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "kanban-ui/**"

env:
  TF_WORKING_DIR: './iac_cloud'
  TF_ENVIROMENTS_PATH: 'environments/'
  MERGE_DELETE_BRANCH: 'true'
  MERGE_LABELS: ''

jobs:
  promotion_branch:
    name: node
    ## TODO: no latest!!!
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install
      - run: npm test