---
name: Angular Frontend CI Flow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
    paths:
      - "kanban-ui/**"

env:
  TF_WORKING_DIR: './iac_cloud'
  TF_ENVIROMENTS_PATH: 'environments/'
  MERGE_DELETE_BRANCH: 'true'
  MERGE_LABELS: ''

jobs:
  promotion_branch:
    name: node
    ## TODO: no latest!!!
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

 ##     - run: npm install
 ##       working-directory: kanban-ui
                
 ##     - run: npm install -g @angular/cli > /dev/null
 ##       working-directory: kanban-ui

      - name: get Artifact version
        id: artmetadata
        run: |
          APP_VERSION=$(cat package.json | jq .version | tr -d '"')
          IMAGE_TAG=ghcr.io/iiglesiasg/kanban-board_kanban-ui:${APP_VERSION}
          echo $IMAGE_TAG
          echo "::set-output name=APP_VERSION::${APP_VERSION}"
          echo "::set-output name=IMAGE_TAG::${IMAGE_TAG}"
        working-directory: kanban-ui

      - name: Docker login
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker build
        run: |
          docker build . --tag ${IMAGE_TAG}
        working-directory: kanban-ui
        env:
          IMAGE_TAG: ${{ steps.artmetadata.outputs.IMAGE_TAG }}


      - name: Docker Push
        run: docker push ${IMAGE_TAG}
        env:
          IMAGE_TAG: ${{ steps.artmetadata.outputs.IMAGE_TAG }}
