---
name: Create Infra

on:
  workflow_dispatch:

env:
  HOST: '168.119.238.196'
  USERNAME: 'ningu'
jobs:
  promotion_branch:
    name: terraform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create Github Issue
        id: issue
        run: |
          ISSUE=$(hub issue create -m 'Creation of Vm in Hetzner Cloud' -a ${{ github.actor }})
          ISSUE_NUMBER=$(basename "$ISSUE")
          echo "::set-output name=ISSUE_NUMBER::${ISSUE}"
          echo "::set-output name=ISSUE_NUMBER::${ISSUE_NUMBER}"
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}

      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
        working-directory: infra/terraform
      - id: plan
        run: terraform plan --var=hcloud_token=${{ secrets.HCLOUD_TOKEN }} -no-color
        continue-on-error: true
        terraform_wrapper: true
        working-directory: infra/terraform

      - name: comment issue
        run: |
          BODY=$(echo "\`\`\`bash\n ${{ steps.plan.output.stdout }}")
          hub api repos/${{ github.repository }}/issues/${{ steps.issue.outputs.ISSUE_NUMBER }}/comments --raw-field "body=${BODY}"
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}

      - name: Terraform Apply
        id: apply
        run: terraform apply --var=hcloud_token=${{ secrets.HCLOUD_TOKEN }} -no-color --auto-approve
        continue-on-error: true
        working-directory: infra/terraform

      - name: comment issue
        run: |
          BODY=$(echo "\`\`\`bash\n ${{ steps.apply.outcome }}")
          hub api repos/${{ github.repository }}/issues/${{ steps.issue.outputs.ISSUE_NUMBER }}/comments --raw-field "body=${BODY}"
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}

