---
name: Github Release

on:
  push:
    branches:
      - "master"
    paths:
      - "docker-compose.yml"


jobs:
  promotion_branch:
    name: Release
    ## TODO: no latest!!!
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Calculate Next Release
        id: new-version
        run: |
          git describe --tags --abbrev=0
          OLD_TAG=$(git describe --tags --abbrev=0)
          OLD_MAYOR_VERSION=$(git describe --tags --abbrev=0 | rev | cut -d '.' -f2- | rev)
          OLD_MINOR_VERSION=$(echo $OLD_TAG | cut -d '.' -f2-)
          NEW_MINOR_VERSION=$(($OLD_MINOR_VERSION + 1))
          NEW_TAG=$(echo "${OLD_MAYOR_VERSION}.${NEW_MINOR_VERSION}")
          git tag $NEW_TAG master
          echo "::set-output name=NEW_TAG::${NEW_TAG}"

      - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ steps.new-version.outputs.NEW_TAG }}
            release_name: Release ${{ steps.new-version.outputs.NEW_TAG }}
            body: |
              Changes in this Release
              - First Change
              - Second Change
            draft: false
            prerelease: false