---
name: Install CD Control Loop

on:
  workflow_dispatch:

env:
  HOST: '168.119.238.196'
  USERNAME: 'root'
jobs:
  promotion_branch:
    name: controller-loop
    runs-on: ubuntu-latest

    steps:
      - name: Get the Key
        run: |
          echo "${{ secrets.PAAK_GITHUB_SSH_RSA_KEY }}" > id_rsa

      - name: Ssh key for github
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.PAAK_SERVER_SSH_RSA_KEY }}
          source: "id_rsa"
          target: "~/.ssh/"
      - name: Connect to server apply commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.PAAK_SERVER_SSH_RSA_KEY }}
          script: |
            sudo chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git clone git@github.com:iiglesiasg/kanban-board.git --single-branch
            sudo cp kanban-board/docker-compose.yml /etc/docker/compose/kanban-board
            sudo systemctl start docker-compose@kanban-board
            sudo chmod +x /etc/docker/compose/kanban-board/cd-convergence.sh
            sudo crontab /etc/docker/compose/kanban-board/crontab-job

