---
name: JavaApp CI Flow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
    paths:
      - "kanban-app/**"

jobs:
  promotion_branch:
    name: java
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots test
        working-directory: kanban-app
      - name: Call Sonar
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar \
            -Dsonar.projectName=paak \
            -Dsonar.password=$SONAR_PASSWORD \
            -Dsonar.host.url=http://$SONAR_IP:9000/ \
            -Dsonar.junit.reportsPath=target/surefire-reports \
            -Dsonar.jacoco.reportPath=target/jacoco.exec
        env:
          SONAR_PASSWORD: ${{ secret.SONAR_PASSWORD }}
          SONAR_IP: ${{ secrets.PAAK_SERVER_IP }}
        working-directory: kanban-app

      - name: get Artifact version
        id: artmetadata
        run : |
          APP_VERSION=$(mvn -q -N org.codehaus.mojo:exec-maven-plugin:3.0.0:exec -Dexec.executable='echo' -Dexec.args='${project.version}')
          IMAGE_TAG=ghcr.io/iiglesiasg/kanban-board_kanban-app:${APP_VERSION}
          echo $IMAGE_TAG
          echo "::set-output name=APP_VERSION::${APP_VERSION}"
          echo "::set-output name=IMAGE_TAG::${IMAGE_TAG}"
        working-directory: kanban-app

      - name: Docker login
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker build
        run: |
          docker build . --tag ${IMAGE_TAG}
        working-directory: kanban-app
        env:
          IMAGE_TAG: ${{ steps.artmetadata.outputs.IMAGE_TAG }}
        

      - name: Docker Push
        run: docker push ${IMAGE_TAG}
        env:
          IMAGE_TAG: ${{ steps.artmetadata.outputs.IMAGE_TAG }}
