---
name: Ssh Connection Test

on:
  workflow_dispatch:

env:
  HOST: '168.119.238.196'
  USERNAME: 'ningu'
jobs:
  promotion_branch:
    name: ssh-test
    runs-on: ubuntu-latest

    steps:
      - name: Ssh key for github
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.PAAK_SERVER_SSH_RSA_KEY }}
          source: ${{ secrets.PAAK_GITHUB_SSH_RSA_KEY }}
          target: "~/.ssh/id_rsa"
      - name: Connect to server apply commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.PAAK_SERVER_SSH_RSA_KEY }}
          script: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git clone git@github.com:iiglesiasg/kanban-board.git --single-branch
            sudo mv kanban-board/docker-compose.yml /etc/docker/compose/kanban-board
            sudo systemctl start docker-compose@kanban-board
            sudo crontab /etc/docker/compose/kanban-board/crontab-job
            sudo chmod +x /etc/docker/compose/kanban-board/cd-convergence.sh

